### ISSUE TITLE
[ADDRESSED] Open Intercom Messenger file upload issue

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/blog#25]
Hello team,

I would like to report two issues with the Open Intercom Messenger. 

Please see the picture below for context on where the messenger is access from, it being endpoint /blog. 👇

![bugreport15](https://github.com/codedex-io/blog/assets/48260426/7fb8923a-6df1-4c55-a83d-9a419bd9bebf)

### Issue 01
Files with extention .php%20 can be uploaded to the messenger. This can be a possible vulnerability as users can upload files with malicious content to it. See picture below.  👇
![bug15](https://github.com/codedex-io/blog/assets/48260426/f3139373-fd98-466b-8806-830d81626a3d)

### Issue 02
The messenger cannot receive more than five uploaded files at once. I tried to upload five different .txt files, and it does not display anything after the files are uploaded, while uploading up to 5 .txt files are correctly shown by the messenger. 

I understand these might not be bugs, and if they are, they might not be Codedex ownership as it seems this messenger can be a third-party software. But still, I am doing this for the points. 🪙

**Comment by sonnynomnom** [comment]
Ah, so looking at this. Like you said here: `they might not be Codedex ownership as it seems this messenger can be a third-party software` this is Intercom's issue and not Codédex's. So I'm closing this one. I won't deduct points for this one this time but if another third-party issue is reported, then I will do so, just to be fair.

**Comment by MilanGrujicic** [comment]
Thanks for not deducting points Sonny, I will stop thinking outside of the box for my own good. =)
