### ISSUE TITLE
missing title tags in blogs

### ISSUE THREAD

**Issue by byt3h3ad** [codedex-io/blog#4]
![image](https://user-images.githubusercontent.com/26319721/236908086-f670585a-0e1c-4d2e-ab55-29f7c82196a0.png)

the blogs don't have a title set which looks a bit ugly to the eye. A simple `Codedex Blog` or the title would look cool too.

![image](https://user-images.githubusercontent.com/26319721/236909038-3a47ff8d-6a1c-464c-ad04-671aed2c3e11.png)

If possible, I want to help fix this and contribute!

**Comment by sonnynomnom** [comment]
This should be fixed! Closing! 🙏
