### ISSUE TITLE
[a11y] Headings need improvement in certificate blog post 

### ISSUE THREAD

**Issue by CBID2** [codedex-io/blog#42]
## Description
I noticed that there were most H4 style headings in the certificate blog post. This can make it harder for readers with disabilities to navigate the blog post.
https://github.com/codedex-io/blog/blob/8ae97de5b2c029fd21965a240f18644b4a805ffa/blogs/certificates.mdx?plain=1#L15-L16
> [!NOTE]
> It also makes the post less SEO-friendly 

## Solution
[It is often recommended to putting heading in chronological order](https://www.boia.org/blog/accessible-headings-are-great-for-users-and-great-for-seo), so some of them can be replaced with `## h2` and `### h3` headings.

**Comment by sonnynomnom** [comment]
https://www.codedex.io/community/monthly-challenge/submission/6gM0M1d0BvsoytCq4jLq

So sorry Christine...
